# Generated by Django 3.2.6 on 2021-08-05 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.TextField()),
                ('lang', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.TextField()),
                ('definition', models.TextField()),
                ('frequency_rank', models.IntegerField()),
                ('lang', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WordEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('context', models.IntegerField(choices=[(1, 'business'), (2, 'academic'), (3, 'literary')])),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.forms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_encounter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='forms',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.lemma'),
        ),
    ]
