# Generated by Django 3.2.6 on 2021-08-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='frequency_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
