# Generated by Django 3.2.6 on 2021-08-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_lemma_frequency_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forms',
            options={'verbose_name': 'Form', 'verbose_name_plural': 'Forms'},
        ),
    ]
