# Generated by Django 3.2.6 on 2021-08-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_forms_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forms',
            new_name='WordForms',
        ),
    ]
