# Generated by Django 3.2.6 on 2021-08-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_rename_forms_wordforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('lang', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='lemma',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wordforms',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
