# Generated by Django 3.2.6 on 2021-08-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_alter_wordforms_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordforms',
            old_name='word',
            new_name='lemma',
        ),
    ]
