# Generated by Django 3.2.6 on 2021-08-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_rename_word_wordforms_lemma'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordforms',
            name='sentence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
