# Generated by Django 3.2.6 on 2021-08-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_wordforms_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordforms',
            name='form',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordforms',
            name='lang',
            field=models.TextField(blank=True, null=True),
        ),
    ]
