# Generated by Django 3.2.6 on 2021-08-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_auto_20210824_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputSentences',
        ),
    ]
