# Generated by Django 3.2.6 on 2021-08-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_delete_inputsentences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordencounter',
            name='sentence',
        ),
        migrations.RemoveField(
            model_name='wordforms',
            name='sentence',
        ),
        migrations.AlterField(
            model_name='wordencounter',
            name='context',
            field=models.IntegerField(blank=True, choices=[(1, 'business'), (2, 'academic'), (3, 'literary')], null=True),
        ),
    ]
