# Generated by Django 3.2.6 on 2021-08-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_auto_20210830_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordencounter',
            name='encounter',
            field=models.CharField(default='ai', max_length=250),
            preserve_default=False,
        ),
    ]
