# Generated by Django 3.2.6 on 2021-08-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0012_wordencounter_encounter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordencounter',
            old_name='form',
            new_name='word_form',
        ),
        migrations.RemoveField(
            model_name='wordencounter',
            name='context',
        ),
    ]
