# Generated by Django 3.2.6 on 2021-08-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0013_auto_20210830_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordencounter',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
