# Generated by Django 3.2.6 on 2021-08-05 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=250)),
                ('lang', models.TextField()),
                ('frequency_rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrammarEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(choices=[(1, 'syntax'), (2, 'spelling'), (3, 'stylistics')])),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_encounter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
